# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TFAnnotator
                                 A QGIS plugin
 Tensorflow Dataset Annotation Tool
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-08-24
        copyright            : (C) 2018 by Seokyong Hong
        email                : shong3@ncsu.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TFAnnotator class from file TFAnnotator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tf_annotator import TFAnnotator
    return TFAnnotator(iface)
